names = {'BIOPRO': 'biochemistry', 
'BMX': 'body_measures', 
'BPQ': 'blood_pressure_cholesterol', 
'BPX': 'blood_pressure', 
'CBQ': 'consumer_behavior', 
'CDQ': 'cardiovascular', 
'CFQ': 'cognitive_functioning', 
'DBQ': 'nutrition', 
'DEMO': 'demographic', 
'DIQ': 'diabetes', 
'GHB ': 'glycohemoglobin', 
'HDL': 'high_dens_lipoprotien', 
'HSQ': 'current_health', 
'INS': 'insulin', 
'KIQ': 'kidney_conditions', 
'MCQ': 'medical_conditions', 
'PAQ': 'physical_activity', 
'PFQ': 'physical_functioning', 
'RXQ': 'Perscriptions', 
'SLQ': 'sleeping_disorders', 
'TCHOL': 'total_cholesterol', 
'TRIGLY': 'cholesterol_low'}

just_names = ['biochemistry',
'body_measures', 
'blood_pressure_cholesterol', 
'blood_pressure', 
'consumer_behavior', 
'cardiovascular', 
'cognitive_functioning', 
'nutrition', 
'demographic', 
'diabetes', 
'glycohemoglobin', 
'high_dens_lipoprotien', 
'current_health', 
'insulin', 
'kidney_conditions', 
'medical_conditions', 
'physical_activity', 
'physical_functioning', 
'Perscriptions', 
'sleeping_disorders', 
'total_cholesterol', 
'Tcholesterol_low']